TEST_POS_ELEC_DIR = "../../../data/Calce_PL/param_pos-electrode.csv"
TEST_NEG_ELEC_DIR = "../../../data/Calce_PL/param_neg-electrode.csv"
TEST_ELECTROLYTE_DIR = "../../../data/Calce_PL/param_electrolyte.csv"
TEST_BATTERY_CELL_DIR = "../../../data/Calce_PL/param_battery-cell.csv"
SEI_DIR = "../../../data/Calce_PL/param_degradation.csv"