TEST_POS_ELEC_DIR = "../data/test/param_pos-electrode.csv"
TEST_NEG_ELEC_DIR = "../data/test/param_neg-electrode.csv"
TEST_ELECTROLYTE_DIR = "../data/test/param_electrolyte.csv"
TEST_BATTERY_CELL_DIR = "../data/test/param_battery-cell.csv"
SEI_DIR = "../data/test/param_degradation.csv"