@startuml
'https://plantuml.com/class-diagram

Electrode <|- PElectrode
Electrode <|- NElectrode

class Electrode {
+ L: float
+ A: float
+ kappa: float
+ epsilon: float
+ max_conc: float
+ R: float # Radius
+ S: Optional[float]
+ T_ref: float
+ D_ref: float
+ k_ref: float
+ Ea_D: float
+ Ea_R: float
+ alpha: float
+ brugg: float
+ SOC_init: float
+ T: float

+ OCP(): float
}

class PElectrode {
+ electrode_type: str = 'p'
}

class NElectrode {
+ electrode_type: str = 'n'
}

@enduml